### ISSUE TITLE
Error: Video sender not found to change bandwidth

### ISSUE THREAD

**Issue by sagark1510** [TecladistaProd/rn-antmedia#2]
@TecladistaProd @eduwr 

I have used the code from the readme.md and as soon as I hit the button join room it just gives me this error. 

<img src="https://user-images.githubusercontent.com/2134076/105955502-688a7080-609c-11eb-8e41-bb06b12a205a.png" width="400">

However, if I just return `Promise.resolve()` instead throwing an error it works. But that's not right thing to do. Can you help me please?

**Comment by eneskuluk** [comment]
I got that error as well but it was streaming anyway in Android. Also i had to add this to gradle.properties to make it workable. I think it is more related to react-native-webrtc requirement. It doesn't work for me without adding the command below.
```
android.enableDexingArtifactTransform.desugaring=false
```

Also don't forget to add the permissions that react-native-webrtc requires.

**Comment by TecladistaProd** [comment]
@eneskuluk , yes to react-native-webrtc work i needed to add this code on gradle.

**Comment by TecladistaProd** [comment]
@sagark1510 , are you using on android or iphone ? because i just tested on android and worked, in console showing this message but working. This error occurs because react-native-webrtc haven't method getSenders yet, but i take a look a way to not throw this error

**Comment by sagark1510** [comment]
@TecladistaProd  I got this error on iPhone. Yeah, least we can do is not throw an error if getSenders is not available.

**Comment by TecladistaProd** [comment]
@sagark1510 , i will push new version with this throw commented, if not work please reopen this issue to me know, thanks.
