### ISSUE TITLE
No event  fires when someone joins to the room

### ISSUE THREAD

**Issue by sagark1510** [TecladistaProd/rn-antmedia#3]
I ran the code from the readme.md 

### Current Behavior:
1. Join from device A
2. Join from device B
3. Device B shows local video as well as remote video
4. Device A doesn't show remoteVideo as remoteStreams doesn't have any new stream
5. No `newStreamAvailable` command gets fired on Device A

### Expected Behavior:
1. Join from device A
2. Join from device B
3. Device B shows local video as well as remote video
4. Device A shows local video as well as remote video
5. `newStreamAvailable` command gets fired

Seems,` onTrack` method is not getting called which is responsible for adding new remoteStreams

**Comment by eneskuluk** [comment]
In the new Ant Media Server conference, there is no newStreamAvailable callback. Client intervally checks if someone joined to the room or not. 

See: https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference

This has been changed in the later versions of Ant Media Server. And now client checks if any stream available in the room or not.

See the example application of conference here: https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L486

It starts the interval in the above link and the callback is: https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/conference.html#L548

Hope this helps.

**Comment by sagark1510** [comment]
@eneskuluk  Yeah, that is one way to find the latest streams and I gonna use that for sure. But what about using `onaddstream` listener to handle the `onTrack` and add new remote stream on the fly to the adapter rather waiting for the interval to get finished and get the roomInformation ?

`ontrack` listener is actually not available by the react native webrtc library. See https://github.com/react-native-webrtc/react-native-webrtc/issues/433 for more info.

**Comment by sagark1510** [comment]
Okay closing this issue as `onaddstream` is deprecated and `ontrack` is not added in the react-native-webrtc. So only way to get the new stream is by fetching the room information periodically.

Thanks @eneskuluk  @TecladistaProd

**Comment by sagark1510** [comment]
I think there are still some issues getting stream using room information which we need to find.

**Comment by sagark1510** [comment]
@TecladistaProd  can you provide some working example with peer to peer or conference ?

**Comment by TecladistaProd** [comment]
@sagark1510 , okay i will work on it.

**Comment by TecladistaProd** [comment]
but apparently this will take more time than i expected, i'll fix some bugs in lib for peer to peer example work, then i'll do conference example first.

**Comment by TecladistaProd** [comment]
@sagark1510 

Sorry, but apparently this will take more time than i expected, i'll fix some bugs in lib for peer to peer example work, then i'll do conference example first.

But don't worry about it, i'm working on it.

**Comment by sagark1510** [comment]
@TecladistaProd I have raised a PR for example https://github.com/TecladistaProd/rn-antmedia/pull/4 
Please take a look.

**Comment by eneskuluk** [comment]
Thanks for the example application @sagark1510
