### ISSUE TITLE
Connecting with SSL not working - "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."

### ISSUE THREAD

**Issue by droidlabour** [TecladistaProd/rn-antmedia#5]
Hi There
First of all thanks for building this library.

For some reason I'm unable to connect with `wss` on default port 5080, however it works with `ws`.
Is there any param that must be passed to connect via SSL?

**Comment by eneskuluk** [comment]
What happens when you try with port 5443 on wss?

**Comment by droidlabour** [comment]
@eneskuluk Both wss & ws fails on port 5443

**Comment by eneskuluk** [comment]
wss was working for me. You have ssl installed right?
Also what happens without specifying port?

**Comment by droidlabour** [comment]
I've ssl configured coz the admin panel works with https at 5443.

Lemme try without specifying the port.

**Comment by droidlabour** [comment]
@eneskuluk Sorry for my late response, I tried without specifying any port, unfortunately It doesn't work.

**Comment by eneskuluk** [comment]
Thanks, i checked my code and confirmed it is working with wss on port 5443.

**Comment by droidlabour** [comment]
Is it possible to share your code?
FYI I'm using the code from that `example` directory.

**Comment by eneskuluk** [comment]
No, i haven't used that. I kinda created mine but it's not that different. I referenced the one on the readme.md.

**Comment by droidlabour** [comment]
I see, I'll try with the `README.md` version.
BTW if possible can you please try your version with this endpoint `https://ant-media.aiyogihealth.com` and see if it works for you?

For the time being, all ports are open for this endpoint.

**Comment by TecladistaProd** [comment]
@droidlabour 
Hi, i'm working on new updates, bug fix and peer to peer work example, and i used your api to test and verify why don't connect with wss://ant-media.aiyogihealth.com:5443/WebRTCAppEE/websocket, and the problem occure in the WebSocket connection in onerror 

`{"isTrusted": false, "message": "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."} `


i found these links about this message https://github.com/facebook/react-native/issues/6058 and https://stackoverflow.com/questions/52400120/java-security-cert-certpathvalidatorexception-trust-anchor-for-certification-pa.

If some of these help to resolve please don't forget to close this issue.

**Comment by SelimEmre** [comment]
Hi guys,

It may related to SSL Chain error -> https://www.sslshopper.com/ssl-checker.html#hostname=https://ant-media.aiyogihealth.com:5443/

Could you please check this issue? https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M/m/C6Cb590VAgAJ
