### ISSUE TITLE
publishTimeoutError

### ISSUE THREAD

**Issue by shakuniyamihir8400** [TecladistaProd/rn-antmedia#6]
![](https://user-images.githubusercontent.com/56870338/108462160-28389f80-72a2-11eb-80e3-625957327034.png)
i'm using rn-antmedia for video calling but its throwing error "publishtimeouterror".
and i dont know why it is happening. have any idea about it???

**Comment by TecladistaProd** [comment]
Hello @shakuniyamihir8400 , as quoted here (https://github.com/ant-media/Ant-Media-Server/issues/2223#issuecomment-781874874) this could be a server error, you tried connect with a web page to see if the same occur ? For me this error occurred to me once when the server was blocked to publish or something like this, but i don't how was resolved, i was just developing the app.
