### ISSUE TITLE
Community Edition

### ISSUE THREAD

**Issue by ciaoamigoschat** [TecladistaProd/rn-antmedia#7]
Hi good job, does it also support Community Edition server?

**Comment by TecladistaProd** [comment]
This is just the adaptor for RN, i think this will work for community version as well. If work fine please don't forget to comment.

**Comment by ciaoamigoschat** [comment]
1) I have installed ant-media server
2) I have activated SSL
3) I downloaded the sample file
4) Configured the react-native-webrtc module
5) Launched the application in Android debugging
6) But it seems that it is connected to the Room.

Do I need to configure anything on the AntMedia server?

**Comment by ciaoamigoschat** [comment]
1) I have installed ant-media server
2) I have activated SSL
3) I downloaded the sample file
4) Configured the react-native-webrtc module
5) Launched the application in Android debugging
6)  **Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.**

Do I need to configure anything on the AntMedia server?

**Comment by TecladistaProd** [comment]
Hi @ciaoamigoschat , here https://github.com/TecladistaProd/rn-antmedia/issues/5.
