### ISSUE TITLE
which method for chat-system implementation???

### ISSUE THREAD

**Issue by shakuniyamihir8400** [TecladistaProd/rn-antmedia#8]

**Comment by TecladistaProd** [comment]
Just audio and video by this moment, probably in future update.

**Comment by shakuniyamihir8400** [comment]
so, Is there any possible way for data transmission for send messages and receive messages?
in webrtc also.

**Comment by TecladistaProd** [comment]
@shakuniyamihir8400 I don't know yet, i'll check this with react-native-webrtc lib and do the update in the rn-antmedia, if not i come here to say.

**Comment by shakuniyamihir8400** [comment]
Any update for that?

**Comment by TecladistaProd** [comment]
Yes, apparently react-native-webrtc accept dataChannel, i'm working in a new update, but will take a little of time.

**Comment by patsiee** [comment]
Any update in dataChannel?

**Comment by TecladistaProd** [comment]
@patsiee  and @shakuniyamihir8400  sorry, i'm working in a staging to production app then i'm not having so much time to my personal projects, but today i'm working here in this task and it looks promising, probably today i finish the update, then i'll create an example and push the update and the example.

**Comment by shakuniyamihir8400** [comment]
@TecladistaProd Thnks a lot man.

**Comment by TecladistaProd** [comment]
You're welcome @shakuniyamihir8400.
@patsiee.
It's done and have an example in examples/example_1 in "Chat" view.

**Comment by patsiee** [comment]
@TecladistaProd Thanks a lot :)

**Comment by TecladistaProd** [comment]
I'm closing this issue if something happen with this new functionality, please open a new issue.
