### ISSUE TITLE
iOS Playing Livestream Crash

### ISSUE THREAD

**Issue by JohnArchlord** [TecladistaProd/rn-antmedia#9]
I tried implementing a livestream code following the Peer view sample code on example folder. On android it works perfectly, both broadcasting and playing livestream but on iOS only broadcasting works, Playing functionality causes App to crash immediately after running adaptor.play. 

The first thing I noticed is that remoteMedia is not picking up anything causing "No video stream for react tag" error at the start of the screen but it only happens on iOS. 

My adaptor on Play screen looks like this: 

![image](https://user-images.githubusercontent.com/82623667/114964058-8e0b6700-9ea0-11eb-8f38-01ec27538719.png)

And my RTCView looks like this: 

![image](https://user-images.githubusercontent.com/82623667/114964758-e8f18e00-9ea1-11eb-8423-e16cc959859e.png)

I turned off video and audio since its just playing a stream and not sending the stream then I turned onlyDataChannel true because it won't let me start the adaptor without video and audio. Again everything works perfectly on android. It only crashes on iOS once I run PlayerAdaptor.play(streamId);

**Comment by Archlorde** [comment]
Looks like react-native-webrtc error 

Here is their current workaround: 

https://github.com/react-native-webrtc/react-native-webrtc/issues/962

**Comment by JohnArchlord** [comment]
Looks like a react-native-webrtc issue

They have provided a workaround: 
https://github.com/react-native-webrtc/react-native-webrtc/issues/962

I tested it now and it works but I will continue testing it

**Comment by JohnArchlord** [comment]
It's not stable enough it still crashes...

**Comment by JohnArchlord** [comment]
Good day @TecladistaProd, can you test if the examples are still working on iOS? 
This issue might have affected the code: https://github.com/react-native-webrtc/react-native-webrtc/issues/962 . The adaptor is not receiving any remote streams on iOS. It works on android but on iOS I'm having "No video stream on react tag" because there is no remote streams present. Thanks in advance.

**Comment by JohnArchlord** [comment]
Hmmmm the issue seems to be that even if I'm not sending a video stream, I still need to set local Stream... I removed it because I thought it was not necessary.

I am once again closing this issue.

**Comment by TecladistaProd** [comment]
Sorry because, I saw it today and unfortunately and I yet don't have a mac to try on apple. But i'll saw if i can fix it.
